name: Apply Terraform Infrastructure

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      terraform_version:
        required: true
        type: string
      deploy_infra:
        type: boolean
        default: false
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  detect-terraform-infra:
    runs-on: ubuntu-latest
    outputs:
      has-terraform: ${{ steps.check.outputs.has_tf }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: |
          if compgen -G "infra/*.tf" > /dev/null; then
            echo "has_tf=true" >> $GITHUB_OUTPUT
          else
            echo "has_tf=false" >> $GITHUB_OUTPUT
          fi

  apply-terraform-infra:
    runs-on: ubuntu-latest
    needs: detect-terraform-infra
    if: needs.detect-terraform-infra.outputs.has-terraform == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Initialize terraform
        run: cd infra && terraform init

      - name: Validate terraform
        run: cd infra && terraform validate

      - name: Plan terraform
        run: |
          cd infra && terraform plan \
            -var-file="${{ inputs.environment }}.tfvars" \
            -var="image_tag=${{ inputs.image_tag }}" \
            -out=tfplan

      - name: Apply terraform
        if: ${{ inputs.deploy_infra == true }}
        run: |
          cd infra && terraform apply -auto-approve \
            -var-file="${{ inputs.environment }}.tfvars" \
            -var="image_tag=${{ inputs.image_tag }}"
