name: Create and Push Docker Image

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '21'
      latest-version:
        required: false
        type: boolean
        default: false
      scan-vulnerabilities:
        description: 'Whether to scan the Docker image for vulnerabilities using Trivy'
        required: true
        type: boolean
        default: true
    outputs:
      image_docker:
        description: 'Full Docker image with tag'
        value: ${{ jobs.create-docker-image.outputs.image_docker }}

permissions:
  contents: read
  packages: write

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    outputs:
      image_docker: ${{ steps.meta.outputs.full_image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure Maven settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
              "id": "nexus-releases",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }
            ,{
              "id": "nexus-snapshots",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]

      # - name: Configure Maven settings.xml
      #   uses: s4u/maven-settings-action@v3.1.0    
      #   with:
      #     githubServer: false
      #     servers: |
      #       [{
      #         "id": "github",
      #         "username": "${{ github.actor }}",
      #         "password": "${{ secrets.GH_PACKAGES_TOKEN }}"
      #       }]
      #     repositories: |
      #       [{
      #         "id": "github",
      #         "url": "https://maven.pkg.github.com/veta-ai/veta-core-shared-libs",
      #         "releases": { "enabled": true },
      #         "snapshots": { "enabled": true }
      #       }]

      - name: Build and Test with Maven
        run: mvn clean package -DskipTests=false

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract Base Version
        id: version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Detected version: $CURRENT_VERSION"
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-.*//')
          echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT
      
      - name: Set output with full image tag
        id: meta
        run: |
          echo "full_image=ghcr.io/${{ github.repository }}:${{ steps.version.outputs.base_version }}" >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: docker-buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-buildx-${{ runner.os }}-

      - name: Build and Push Docker image to GitHub Packages
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
          IMAGE_TAG: ${{ steps.version.outputs.base_version }}
          LATEST_VERSION: ${{ inputs.latest-version }}
        run: |
          BUILD_CMD="docker buildx build --provenance=false --platform linux/amd64 --tag $IMAGE_NAME:$IMAGE_TAG"

          if [ "$LATEST_VERSION" == "true" ]; then
            BUILD_CMD="$BUILD_CMD --tag $IMAGE_NAME:latest"
          fi

          BUILD_CMD="$BUILD_CMD --push --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache ."

          echo "::group::Docker Build Command"
          echo "$BUILD_CMD"
          echo "::endgroup::"

          eval "$BUILD_CMD"

      - name: Scan Docker Image for Vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@0.31.0
        if: ${{ inputs.scan-vulnerabilities }}
        continue-on-error: true
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
          IMAGE_TAG: ${{ steps.version.outputs.base_version }}
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
          ignore-unfixed: true
