name: Create and Push Docker Image

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '21'
      latest-version:
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  create-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract Base Version
        id: version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-.*//')
          echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image to GitHub Packages
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
          IMAGE_TAG: ${{ steps.version.outputs.base_version }}
          LATEST_VERSION: ${{ inputs.latest-version }}
        run: |
          BUILD_CMD="docker buildx build --platform linux/amd64 --tag $IMAGE_NAME:$IMAGE_TAG"
          
          if [ "$LATEST_VERSION" == "true" ]; then
            BUILD_CMD="$BUILD_CMD --tag $IMAGE_NAME:latest"
          fi

          BUILD_CMD="$BUILD_CMD --push --cache-to=type=inline ."

          echo "Running build command: $BUILD_CMD"
          eval $BUILD_CMD
