name: Build & Test Java Project (Maven)

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '21'

permissions:
  contents: write
  packages: write

jobs:
  prepare-rc:
    name: Prepare RC Version & Deploy
    runs-on: ubuntu-latest
    outputs:
      next_rc_version: ${{ steps.rc.outputs.next_rc_version }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: ${{ github.head_ref }}

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure Maven settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
              "id": "nexus-releases",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }
            ,{
              "id": "nexus-snapshots",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]
          repositories: |
            [{
              "id": "nexus-releases",
              "url": "http://18.223.125.35:8081/repository/maven-releases/",
              "releases": { "enabled": true },
              "snapshots": { "enabled": false }
            },
            {
              "id": "nexus-snapshots",
              "url": "http://18.223.125.35:8081/repository/maven-snapshots",
              "releases": { "enabled": false },
              "snapshots": { "enabled": true }
            }]
          mirrors: |
            [{
              "id": "nexus-snapshots",
              "name": "Nexus Snapshots",
              "mirrorOf": "nexus-snapshots",
              "url": "http://18.223.125.35:8081/repository/maven-snapshots/"
            },
            {
              "id": "nexus-releases",
              "name": "Nexus Releases",
              "mirrorOf": "nexus-releases",
              "url": "http://18.223.125.35:8081/repository/maven-releases/"
            }]
  
      # - name: Configure Maven settings.xml
      #   uses: s4u/maven-settings-action@v3.1.0    
      #   with:
      #     githubServer: false
      #     servers: |
      #       [{
      #         "id": "github",
      #         "username": "${{ github.actor }}",
      #         "password": "${{ secrets.GH_PACKAGES_TOKEN }}"
      #       }]
      #     repositories: |
      #       [{
      #         "id": "github",
      #         "url": "https://maven.pkg.github.com/veta-ai/veta-core-shared-libs",
      #         "releases": { "enabled": true },
      #         "snapshots": { "enabled": true }
      #       }]

      - name: Extract Base Version
        id: version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Detected version: $CURRENT_VERSION"
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-.*//')
          echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT

      # - name: Validate branch
      #   if: github.ref != 'refs/heads/release' && github.ref != 'refs/heads/main'
      #   run: |
      #     echo "🚫 RCs devem ser gerados apenas de develop ou main"
      #     exit 1

      - name: Calculate Next RC Version
        id: rc
        run: |
          git fetch --tags
          BASE=${{ steps.version.outputs.base_version }}
          TAGS=$(git tag -l "v${BASE}-RC*" || true)
          echo "Existing RC tags:"
          echo "$TAGS"

          RC_NUMBER=1
          if [[ ! -z "$TAGS" ]]; then
            LAST_RC=$(echo "$TAGS" | sed -E 's/.*-RC([0-9]+)/\1/' | sort -nr | head -n1)
            RC_NUMBER=$((LAST_RC + 1))
          fi

          NEW_VERSION="${BASE}-RC${RC_NUMBER}"
          echo "next_rc_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Set RC Version
        run: |
          mvn versions:set -DnewVersion=${{ steps.rc.outputs.next_rc_version }}
          mvn versions:commit

      - name: Deploy RC Version
        run: mvn clean deploy -DskipTests --batch-mode

      - name: Commit RC Version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if ! git diff --cached --quiet; then
            git commit -am "chore(release): set RC version ${{ steps.rc.outputs.next_rc_version }}"
            git push
          else
            echo "No changes to commit"
          fi


  tag-rc:
    name: Generate new Tag RC
    needs: prepare-rc
    runs-on: ubuntu-latest
    env:
      RC_VERSION: ${{ needs.prepare-rc.outputs.next_rc_version }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: ${{ github.head_ref }}

      - name: Tag RC Version
        run: |
          git tag "v$RC_VERSION"
          git push origin "v$RC_VERSION"