name: CI - Release → RC com Versão, Tag e Build

on:
  workflow_call:
    inputs:
    
      java-version:
        required: false
        type: string
        default: '21'

      terraform-version:
        required: false
        type: string
        default: '1.9.6'

      sonar_project_key:
        required: false
        type: string
      
      scan-vulnerabilities:
        description: 'Whether to scan the Docker image for vulnerabilities using Trivy'
        required: true
        type: boolean
        default: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-java-maven.yaml
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
      sonar_project_key: ${{ inputs.sonar_project_key }}
      type_application: 'java-application'

  create-docker-image:
    name: Create Docker Image
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/create-docker-image.yaml
    with:
      java-version: ${{ inputs.java-version }}
      scan-vulnerabilities: ${{ inputs.scan-vulnerabilities }}

  deploy-artifact:
    name: Validate and Version RC
    needs: create-docker-image
    uses: ./.github/workflows/deploy-java-maven-release-candidate.yaml
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}

  deploy-argo-cd:
    name: Deploy to Argo CD
    uses: ./.github/workflows/deploy-argo-cd.yaml
    needs: [create-docker-image]
    secrets: inherit
    with:
      namespace: 'hom'
      image-docker: ${{ needs.create-docker-image.outputs.image_docker }}

  # apply-terraform:
  #   uses: ./.github/workflows/apply-terraform-infra.yaml
  #   needs: [create-docker-image]
  #   secrets: inherit
  #   with:
  #     terraform_version: ${{ inputs.terraform-version }}
  #     base_version: ${{ needs.deploy-artifact.outputs.next_rc_version }}
  #     deploy_infra: false