name: CI - Feature Validation (Java Library)

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '21'
      base-branch:
        required: false
        type: string
        default: 'develop'
      sonar_project_key:
        required: true
        type: string

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    name: Build & Test
    if: startsWith(github.ref, 'refs/heads/feature/')
    uses: ./.github/workflows/build-java-maven.yaml
    with:
      java-version: ${{ inputs.java-version }}
      sonar_project_key: ${{ inputs.sonar_project_key }}

  open-pr:
    needs: build
    uses: ./.github/workflows/open-pr.yaml
    with:
      base-branch: ${{ inputs.base-branch }}
    secrets: inherit