name: CI - Final Release (Java Library)

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '21'
      sonar_project_key:
        required: false
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-java-maven.yaml
    with:
      java-version: ${{ inputs.java-version }}
      sonar_project_key: ${{ inputs.sonar_project_key }}

  prepare-release:
    name: Prepare & Deploy Final Version
    needs: build
    uses: ./.github/workflows/deploy-java-maven-release.yaml
    with:
      java-version: ${{ inputs.java-version }}
    secrets: inherit